### ISSUE TITLE
Change Update Time

### ISSUE THREAD

**Issue by hunter99507** [hollanbm/renamarr#54]
Is there a way i can change from updated each hour to once every 24 hours?

**Comment by hollanbm** [comment]
> Is there a way i can change from updated each hour to once every 24 hours?

The native scheduler is not configurable. I looking into this, and ultimately just decided not to since kubernetes has its own cron scheduler.

However, you can use docker and cron to externally schedule whenever you would like.

This was added with helm/kubernetes support.

Set the following env variable `EXTERNAL_CRON=true`

That will disable the internal scheduler, and the application will terminate after its first execution.

Then you can schedule via system cron

```shell
$ crontab-e
0 0 * * * /usr/bin/docker start renamarr
```

That will start renamarr at midnight
